using System;
using System.IO;
using System.Reflection;
using NUnit.Framework;
using OpenRA.Mods.Common.AudioLoaders;

namespace OpenRA.Test
{
	[TestFixture]
	public class OggStreamOwnershipTest
	{
		// Synthetic 10 ms stereo tone generated locally with FFmpeg's Vorbis encoder.
		const string Tone =
			"T2dnUwACAAAAAAAAAADKma6iAAAAABhvLh0BHgF2b3JiaXMAAAAAAoC7AAAAAAAAAAAAAAAAAAC7AU9nZ1MAAAAAAAAAAAAAypmu" +
			"ogEAAAC4rg18Dj3///////////////+7A3ZvcmJpcw0AAABMYXZmNjIuMTIuMTAxAQAAABwAAABlbmNvZGVyPUxhdmM2Mi4yOC4x" +
			"MDEgdm9yYmlzAQV2b3JiaXMcQkNWAgAQAACEdJpZqgEizECGgdCQlQAAAgAAYIQiDDEgNGQlAAAQAAAghpKDaEJrzjfnOGiWg6ZS" +
			"bE4HJ1JtnuSmYm7OOeecc7I5Z4xzzjmnKGcWg2ZCa845JzFoloJmQmvOOedJbB60pkprzjlnnHM6GGeEcc45p0lrHqRmY23OOWdB" +
			"a5qj5lJszjknUm6e1OZSbc4555xzzjnnnHPOOad6cToH54Rzzjknam+u5SZ0cc4555NxujcnhHPOOeecc84555xzzjknCA1ZCQAA" +
			"AQAQhGFjGHcKgvQ5GohRhJiGTHrQPTpMgsYgp5B6NDoaKaUOQkllnJTSCUJDVgIAgAAAEEJIIYUUUkghhRRSSCGFGGKIIYaccsop" +
			"qKCSSiqqKKPMMssss8wyyyyzDjvrrMMOQwwxxNBKK7HUVFuNNdaae8655iCtldZaa62UUkoppZSC0JCVAAAIAACBkEEGGWQUUkgh" +
			"hRhiyimnnIIKKiA0ZCUAAAYAwCFnoIEGGmiggQYaaKBxxhmIIIIIIqikkkw6Cim12GrMMddegw46955777n4HIRSSimllFJKKaWU" +
			"UkopJQgNWQkAgAAAAAghhBBSSCGFFFKKMcYccw46CSUEQkNWAgBgAAAMMcQYZJBBSCGFGGKKKccccww6CCGUUlJooYVcaoglllZa" +
			"iaWlmGqLsdZYc+0x1t5777333nvvvffee86B0JCVAEAEAACDDCKIIIKMMQYhBISGrAQAQAAAEGKIMcYghBBSiCGnnIJMMumko5AC" +
			"oSErAQAnAACEEUckcQQSZ6CBCCqpIKPMQiyxtdZaa6211lprrbXWWmuttdZaa6211lprrbXWWmstEBqyEgCIAABgkEEGGUQQQQQZ" +
			"ZIDQkJUAAAgAACOMQAQZpRRjjjnmGHTQQScdhRZaIDRkJQDgBABAIKGIMswwBBFVVFFGFVUUUkcppZRSSimllFJKKaWUUkoppZRS" +
			"SimllFJKKaVUSimlBEJDVgIAZAAAkKKUUiktRYIipRikGEtGFXNQWoqocgxSzalSziDmJJaIMYSUk1Qy5hRCDELqHHVMKQYtlRhC" +
			"xhik2HJLoXMOCA1ZIQCEZgA4HAeQLAuQLAsAAAAAAAAAJE0DNM8DLM0DAAAAAAAAAEnTAMvTAM3zAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQNA3QPA/QPA8AAAAAAAAANM8DPE8EPFEE" +
			"AAAAAAAAAMvzAE30AE8UAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAACQNA3QPA/QPA8AAAAAAAAALM8DPFEENE8EAAAAAAAAAMvzAE8UAU/0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAACjgAAApYCIWG" +
			"rAgA4gQAHJIESYIkQfMAkmVB06BpME2AZFnQNGgaTBMAAAAAAAAAAAAASdOgadA0iCJA0jRoGjQNoggAAAAAAAAAAACApGnQNGga" +
			"RBEgaRo0DZoGUQQAAAAAAAAAAADAM02IIkQRpgnwTBOiCFGEaQIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAACRwAAAVMKAOFhqwI" +
			"AOIEAByOYlkAAOA4jmUBAIDjOJYFAACWZYkiAABYliaKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAJHAAABUwoA4WGrAQAogAAHIpiWcBxLAs4jmUBSbIsgGUBNA+gaQBRBAACAAANHAAA" +
			"BWzQlFgcoNCQlQBAFACAQXEsS9NEkSRpmuaJIknSNM8TRZrmeZ5nmvA8zzNNiKIomiZEURRNE6ZpmqoKTFNVBQAAGjgAAArYoCmx" +
			"OEChISsBgJAAAIeiWJameZ7niaJpqiZJ0jTPE0VRNE3TVFWSpGmeJ4qiaJqmqaosS9M8TxRF0TRVVVWhaZ4niqJomqqquvA8zxNF" +
			"UTRNVXVdeJ7niaIomqaqui5EURRN0zRVU1VdF4iiaZqmqqqq6wLRE0XTVFXXdV3geaJomqrqqq4LRNM0VVVVXVeWAaZpmqrqurIM" +
			"UFVVdV3XlWWAqqqq67quLANU1XVdV5ZlGYDruq4sy7IAAEAEBwBAASPoJKPKImw04cIDUGjIigAgCgAAMIYpxZQyjEkIKYSGMQkh" +
			"hZBJSam0lCoIqZRUSgUhlZJKySillFpKFYRUSiqlgpBKSaUUAACL4AAAi2AhFBqyEgDIAwAgjFGKMcackwgpxZhzzkmElGLMOeek" +
			"Uow555xzUkrGHHPOOSmlc84555yUkjnnnHNOSumcc845J6WU0jnnnJNSSgmhc9BJKaV0zjnnBACAGjgAAArYKLI5wUhQoSErAYBU" +
			"AACD41iWpnmeKJqmJUma5nmeJ4qmqUmSpnme54miavI8zxNFUTRNVeV5nieKomiaqsp1RdE0TVNVVZcsi6Jpmqaqui5M0zRV1XVd" +
			"F6Zpmqrquq4L21ZVVXVdWYZtq6qquq4sA9d1XVm2ZSDLriu7tiwAAF7BAQDUwIbVEU6KxgILDVkJAGQAABDGIKQQQkgZhJBCCCGl" +
			"FEICAAAJHAAABUwoA4WGrAQAUgEAAGOstdZaa6010FlrrbXWWisgs9Zaa6211lprrbXWWmuttdRaa6211lprrbXWWmuttdZaa621" +
			"1lprrbXWWmuttdZaa6211lprrbXWWmuttdZaa6211lpLKaWUUkoppZRSSimllFJKKaWUUgFAvxYOAP8QNqyOcFI0FlhoyEoAIBwA" +
			"ADBGKcYcg1BKKRVCjDknHZXWYqwQYsw5CSm1FlvxnHMQSkiltRiL55yDUEpKsdVYVAqhlJRSiy3WolLoqKSUUms1FmNMKqm11mKr" +
			"sRhjUgottdZijMUIW1NqLbbaaizG2JpKCy3GGGMxwhcZW4uptlqDMcLIFktLtdYajDFG99Ziqa3mYowPvrYUS4w1FwDg7uAAgKhg" +
			"4wwrSWeFo8GFhqwEAEICAAiElGKMMcacc845qRRjjjnnnIMQQiiVYowx55yDEEIIJWOMOecchBBCCKGUkjHnHIQQQgghpJQ65xyE" +
			"EEIIIYRSSuecgxBCCCGEUErpIIQQQgghhBJKKSmFEEIIIYQQQioppRBCCKGUEEpIJaUUQgghhFBKCSmllEIIoZQQQighpZRSSiGE" +
			"EEIppaSUUkqphFJCCaGEVEpKKYUSQgillJJSSimVUkIooYRSSkkppZRSCCGEUkoBAIAIDgCAAkbQSUaVRdhowoUHIAAAAAQAIAiR" +
			"GSJRsAAMDlQAQsIUAFBYYJADAA0OD2kXF9BlgAu6uOtACEEIQhCLAyggAQcn3PDEG55wgxN0ikoNCAAAAAAAGQB8AAAkD0BERDRz" +
			"EBESExQVFhcYGRobHAAAgAACAAAQAAAAAAAIAAAAABBPZ2dTAAQAAgAAAAAAAMqZrqICAAAAwzy8/gT/K/96nlfTNkV2gdiSENyE" +
			"zFqEHE15NW1TZBeILQnBTcisRcjR9KOGSoVKhZoaWQcA4J6YmJg4Y7Asy6qqqhAAAKi1iFrEWlVrpFCtZgSCCKiKmKZhWE3DsFoN" +
			"1Vya6k0tjUYLS63W3FwqkUREXByORMKoFI214+PDMD5hNIxPGA3j48MwNtaORsFWgKaTdHo0TY8eTdOjR6fp0aNpOp2kaUiqaNuq" +
			"brdtu9227Xbbttttq21LlYi8tfvFixcvXtxaCrjP9+v369evX5/vs01kaveLFy9evLi1THDvnu/X79fvc3fNcHx8fHw8jv3/////" +
			"f6lhbHx8fDyO/f/////vw9j4+Ph4HPz/////+zA2Pj4+Hgf//////z4Mx8fHx4H9////rzAcHx8fh/9/BR4mQ1lKmkLoQxRCFIeF" +
			"hAiToSwlTSH0IQohisNCQvwQGRlZlEVZlJVqHQCAc8YYTZZlWa6qqqpaUGOtKMaqpSxSZGRkZGSkomoV1aiTqk5vMDWztEhMookk" +
			"TBAfExsJhYNoTHxcwgQJEyRMkDBBwgQJEyRMEB8XHxcbE41EAwvkIIxEY2Jj4uPi4+Lj4uPie/Ts0bNHt9Nt2lRIpW26nW6n26Nn" +
			"j549evbo2aNnp9vpNm1TKaTSNm2n2+l2up1uj549up1up9tpmzYVVCpt0zbdTrfT7XQ73U63023apk2l0PO/evXq1atXr169OkaI" +
			"qpcvX758+fLly5d6mZ559erVq1evXr16NSNQ9bx8+fLly5cv9SrDzLx69erVq1evZkaYFxcXFxcX2S8vLy8vL7TFxcXFxUX2y8vL" +
			"y8sLLC4uLi4uwsvLy8tLChYXFxcXK/B8eXl5ScFycXFxsQLPl5eXFw+Wi4uLizY8X15eXjyYFxcXF224X14A";

		[Test]
		public void DecoderClosesItsIndependentInputWithoutTakingOwnershipOfTheMetadataInput()
		{
			using var input = new MemoryStream(Convert.FromBase64String(Tone));
			var format = new OggFormat(input);
			using var decoded = format.GetPCMInputStream();
			var clone = typeof(OggFormat.OggStream).GetField("format", BindingFlags.Instance | BindingFlags.NonPublic).GetValue(decoded);
			var clonedInput = (Stream)typeof(OggFormat).GetField("stream", BindingFlags.Instance | BindingFlags.NonPublic).GetValue(clone);
			format.Dispose();
			Assert.That(input.CanRead, Is.True, "The public format borrows its input.");
			input.Dispose();
			var pcm = decoded.ReadAllBytes();
			Assert.That(pcm.Length, Is.GreaterThan(0), "Decoder must outlive metadata and original source.");
			Assert.That(pcm.Length % 4, Is.Zero);
			Assert.That(clonedInput.CanRead, Is.False, "Each repeat must release the cloned encoded input.");
		}
	}
}
